### ISSUE TITLE
Simple yes no command

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#110]
> 💡 This issue is perfect for a Miunie beginner. 

> Feel free to ask about anything you might not understand. 😉 

It would be fun to implement a command like this:
```
User: @Miunie what do you think?
Miunie: Sure
```
```
User: @Miunie what do you think?
Miunie: I don't know...
```
```
User: @Miunie what do you think?
Miunie: Nah
```
Point being it would be a random Yes/No/Maybe answer.

----
## How this should be done

> Thank you to @DraxCodes for helping with this this. ❤️ 

1. Create `MiscService.cs`

This feature should be provided by a `MiscService` (standing for Miscellaneous service).

This new `MiscService.cs` fits in nicely to where all the other services are, that is:

`Miunie/src/Miunie.Core/Services`

> ℹ️ For now if you create `MiscService.cs` it will generate `namespace Miunie.Core.Services` inside the file. You should change it to `namespace Miunie.Core`.

2. Add `IDiscordMessages` dependency

In your `MiscService` create a constructor that will get `IDiscordMessages messages` passed into it as a parameter and store it in a local field. 💡 See [this example](https://github.com/control-net/Miunie/blob/master/src/Miunie.Core/Services/TimeService.cs#L14) for inspiration.

> ℹ️ The `IDiscordMessages` gives your service the ability to send discord messages. You don't need to set anything up, it's kind of cool. 😊 

3. Add a language resource

Miunie needs to know what to say in response.

You should create a new language entry by editing the `Miunie/src/Miunie.Core/Strings.resx` file. (💡 you should open this file from Visual Studio for a better editting experience)

Ideally you would create a single key: `YES_NO_MAYBE` with the different output values being separated with `{{OR}}`

💡 Example:
![Image](https://i.gyazo.com/68cdf83b16e25f64bddbaddd4e8d7099.png)

> This would in effect give it the randomness because we already pick a random value if your entry contains `{{OR}}` directives.

4. Add your key into the phrases enum

In the previous step you defined `YES_NO_MAYBE` as the Key of your language entry. We now need to add it to the PhraseKeys.

All you need to do is add the entry into the `src/Miunie.Core/Entities/PhraseKey.cs` enum.

5. Create a service method 

In your `MiscService.cs` you should create a new method. Give it a descriptive name, something like `SendRandomYesNoAnswer`. 

This method should have the following signature:
`public async Task SendRandomYesNoAnswer(MiunieChannel channel)`

> ℹ️ just like other service methods do, for example [this one](https://github.com/control-net/Miunie/blob/master/src/Miunie.Core/Services/TimeService.cs#L21).

In this method, simply call `await _messages.SendMessage(` and pass in the `MiunieChannel` you got passed into this method and the `PhraseKey` you defined in the previous step.

> ℹ️ The `_messages` comes from step 2

6. Create a command module

The last step is to create a command module in `src/Miunie.Discord/CommandModules`. Something like `MiscCommands.cs` should be fine.

Create your module similar to [this example](https://github.com/control-net/Miunie/blob/master/src/Miunie.Discord/CommandModules/RemoteRepositoryCommand.cs).

The only difference between your implementation and the [example](https://github.com/control-net/Miunie/blob/master/src/Miunie.Discord/CommandModules/RemoteRepositoryCommand.cs) is that instead of `RemoteRepositoryService`, you want to ask for `MiscService` you defined in step 1.

You only need to require it in the constructor, nothing else needs to be done for it to get injected, though you do want to store it in a private field `_miscService` or similar.

The [command attribute](https://github.com/control-net/Miunie/blob/master/src/Miunie.Discord/CommandModules/RemoteRepositoryCommand.cs#L20) should be `"what do you think?"` 

Then you need to convert the channel into `MiunieChannel` like [this](https://github.com/control-net/Miunie/blob/master/src/Miunie.Discord/CommandModules/RemoteRepositoryCommand.cs#L24) inside your command.

The last this is to call `await _miscService.SendRandomYesNoAnswer(channel);`

7. Profit

🎉 Congrats! You did it, it's time to test your code and submit your changes! If you need help with running the bot or submitting your changes, feel free to contact either me (@petrspelos or @DraxCodes  on our [discord server](https://discord.gg/cGhEZuk), we'll be more than happy to help you out). ❤️

**Comment by lopezayl** [comment]
Hello! I'm interested in helping with this feature. First time contributor here, eager to learn! Experience in C, hoping it transfers over to C#... Let me know if I can be assigned to this issue.

**Comment by petrspelos** [comment]
Hello, @lopezayl!
Welcome! By all means, we're really glad you decided to help out.
If you have any questions, feel free to ask. And of course this task is all yours. 😊

**Comment by petrspelos** [comment]
Also, if you'd like a more direct Q&A experience, we have a [Discord server](https://discord.gg/cGhEZuk) you can join. Once you read and accept the rules, there is a #miunie-dev channel just for this project. 🙂

**Comment by petrspelos** [comment]
Architecture got reworked, the issue is now applicable again. 🎉

**Comment by DraxCodes** [comment]
## New Implementation

The Service implementation (MiscService) still applies the same as above.

We have moved our string resources (previously found in the Lang.json files) into `Strings.resx`
This is where you can define new Keys & Values. 

Ideally you would have a single key: `YES_NO_MAYBE` with the different output values being seperated with `{{OR}}` Example:
![Image](https://i.gyazo.com/68cdf83b16e25f64bddbaddd4e8d7099.png)
This would in effect give it the randomness because we already pick a random value in the method: `GetPhrase()`

The rest of the implementation would still be the same:
*Inside the MiscService call SendMessage from IDiscordMessages and pass in the new Phrase. `YES_NO_MAYBE.`*

**Comment by DraxCodes** [comment]
Due to this issue being open for nearly a month now and it being a nice easy beginer freindly one, It is now open again for someone else to take.

**Comment by Ggglitch** [comment]
Since noone is interested in this one, I'm gonna grab it :)

**Comment by Hantick** [comment]
I'm interested in doimg this

**Comment by DraxCodes** [comment]
Sadly this issue is blocked while we implement some side features. If you want to keep up to date with the latest projects we are doing though, please feel free to join our Discord Server. You can find a link to it on the main page of this Repo :)

**Comment by petrspelos** [comment]
This is yet again up for grabs. 😊 

![bitmoji](https://render.bitstrips.com/v2/cpanel/46b92545-79d9-4e83-8ea9-8c7b5cc406aa-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)
