### ISSUE TITLE
Incorrect default connection status

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#133]
> 🌞 This issue is **perfect** for a first-time contributor with a Windows 10 machine. 💻 

## Description

When the UWP (Universal Windows Platform) application starts up, the connection status shows `Not connected`. However, the status is actually generated by calling a `.ToString()` on top of the `ConnectionState` enum, as demonstrated here:
https://github.com/discord-bot-tutorial/Miunie/blob/be3c7434787aceb669c00c013885b1b07bb487b2/src/Miunie.WindowsApp/ViewModels/StatusPageViewModel.cs#L36

The current default status is hard-coded in the constructor:
https://github.com/discord-bot-tutorial/Miunie/blob/be3c7434787aceb669c00c013885b1b07bb487b2/src/Miunie.WindowsApp/ViewModels/StatusPageViewModel.cs#L40-L45

The task is to change the hard-coded value into a string gotten from an enum similar to the first example.

## How can I take this issue?

We recommend you first follow the [CONTRIBUTING](https://github.com/discord-bot-tutorial/Miunie/blob/master/docs/CONTRIBUTING.md) guide to make sure you get a development environment ready.

Then you can comment under this issue that you'd like to take it. 🙂 👍 

Once you get an approval, you'll be invited to become a Contributor, feel free to accept the invite.

_(If you don't accept the invite, you won't be assigned to the issue here on GitHub, but you can still complete it. It's just a GitHub thing we gotta do to assign you.)_ ;)

**Comment by TimmmyGotPasion** [comment]
I PEED ON IT so its mine now.
(not sure if i can complete this, i will probably need help from senpai)

**Comment by petrspelos** [comment]
As @DraxCodes mentioned in Voice Chat, this cannot be completed because the Discord layer currently has no way of detecting that it temporarily disconnected, and no wrapper supports it at this time. 🙁

**Comment by svr333** [comment]
> 
> 
> As @DraxCodes mentioned in Voice Chat, this cannot be completed because the Discord layer currently has no way of detecting that it temporarily disconnected, and no wrapper supports it at this time. 🙁

What about the disconnected event (on top of the Client)

**Comment by petrspelos** [comment]
From what I understood from @DraxCodes, that doesn't trigger for a temporary disconnect.

**Comment by svr333** [comment]
Well that sucks, if that really is the case we could technically run a timer to check so every x minutes, but I don't think that's really worth it.

**Comment by petrspelos** [comment]
As part of the priority adjustments, I'm closing this issue. No worries, we'll get other beginner friendly issues soon.

![bitmoji](https://render.bitstrips.com/v2/cpanel/c356c173-1b6e-4122-b6eb-c703adb3bb4d-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)
