### ISSUE TITLE
Phrase Based Command Handler

### ISSUE THREAD

**Issue by DraxCodes** [control-net/Miunie#176]
Create a handler in Miunie.Discord that hooks into message recieved event. 
This new handler would trugger services based on phrases. 
The command that should be integrated into this new system is the command: `"what do you think?"`

* (Ensure that a Mention Prefix @BotName is present)

**Comment by DraxCodes** [comment]
This will allow for the merge of PR #173

**Comment by petrspelos** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/e4f91d37-026a-44d0-91ea-b26cfdaa34a7-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)

Let's do this one during LiveShare. It is a bit more complex than that.

**Comment by Naamloos** [comment]
I'm not sure about this, but you could check out Quahu's Qmmands. Maybe that one supports whitespaces in command names.

Just a suggestion, haven't looked into it too deeply.

**Comment by Quahu** [comment]
@Naamloos it doesn't as Qmmands uses whitespace (and optionally, a custom separator) for separating aliases such as `group command` or `group1 group2 command`. Even if it did support them, this should definitely be handled by some custom parser tailored to whatever features this would support. It could then invoke commands manually using the various ExecuteAsync overloads, of course.
