### ISSUE TITLE
Implement Currency API Command

### ISSUE THREAD

**Issue by DraxCodes** [control-net/Miunie#178]
### This command would have the following functions:
* Converting from CZK to Anything else (USD)
* See the current conversion rates. (CZK)
* See the conversion rates for last month (CZK)

### Other welcome functions (Optional):
* Convert from any currency to any other currency but for now, have _CZK_ as a default.
* Same as above for both current conversion rates and conversion for the last month, have the ability to also use the command from any currency to any other currency.
* Have the discord output for the commands be as an embed.
* Have a graph for the last months conversion rates.
  * _**Note:** Some (Not all) currency API's already have an API endpoint for getting image based graphs for the above mentioned optional function:_
![Image](https://i.gyazo.com/0705ac8181d4b3c3c63a79fe88b2965f.png)

_**Remeber:** These "Other functions" are all optional, the main 3 required are at the top._

-------

### 💡 Some Ideas
* You would ideally be using an API such as WolframAlpha.
  * _**NOTE:** You don't actually have to use the above mentioned API. This is purely a suggestion as it would also allow us to possibly implement more features from WolframAlpha in the future._
* You can use a Wrapper to access your API of choice if you desire.
* Counter to the above suggestion, you can also choose to write your own wrapper for the functionality needed (Mentioned above).

------

### ℹ️ Notes:
* This command can be as simple or as complicated as you want to make it. That being saifd though, it would be ideal if you could follow the Miunie architecture when deciding to take the issue on. 
* Also note that if you choose to implement this functionality without using a wrapper, you would also need to add unit tests for your code. 
  * _**NOTE:** We can provide help on this if you require it. If you are comfortable implementing the command but aren't comfortable implementing the UnitTest then please note so when you make a PR._

**Comment by petrspelos** [comment]
Alright, I'll go for this.
![bitmoji](https://render.bitstrips.com/v2/cpanel/6b0a4399-7a8d-44a3-b5d3-a8521208c28c-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)

**Comment by petrspelos** [comment]
The base is done, anyone can feel free to expand on the concept.
![bitmoji](https://render.bitstrips.com/v2/cpanel/7218c89b-a039-4a96-bab6-67c159880d85-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)

**Comment by petrspelos** [comment]
Since nobody really went for this, let's just close it for now. We should focus on newer issues for now.

![bitmoji](https://render.bitstrips.com/v2/cpanel/29c5dd71-0876-4f5f-ab95-339aa404a64a-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)
