### ISSUE TITLE
Reputation Listing

### ISSUE THREAD

**Issue by TheBrohman** [control-net/Miunie#180]
Make it possible for a user to see how many Reps the user has received and given.

**Comment by TheBrohman** [comment]
I will work on this whenever I figure out how to Assign myself to it.. If I even can do that.

**Comment by DraxCodes** [comment]
How many reps the user has recieved is already displayed on the `Profile` command. 
I like the idea of also displaying how many reps they have given too so that would implement nicely into the Profile.

If you want to also extend this idea more with a `rep list` command, that would be awesome :)
* Would display the top 5 people with the highest rep

**Comment by DraxCodes** [comment]
Apologies, miss-click 👍

**Comment by petrspelos** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/18ae1ae6-24b5-49ae-86d0-d318dec6b720-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)
I like the idea! =)
Maybe even who the last rep was given to and who gave you rep last?

**Comment by TheBrohman** [comment]
I like that. I was also imagening something like.
A command **rep list user/self** and it would show a list, paged, of all the reps you have given and received, with what the rep was for etc.

**Comment by AbnerSquared** [comment]
I think I could implement these features:
- Update `profile` command to include Reps Awarded along with Reps Received
- `rep` command (no args) could show you the most recent rep you received, alongside the most recent one sent
- `rep list` (optional arg `page`) could show you the list of reps you received (ordered by descending)
- `rep history` (optional arg `page`) could show the list of reps you sent (ordered by descending)

**Comment by petrspelos** [comment]
Thank you, @AbnerSquared!
I'm looking forward to your implementation. 😊 Also let's keep those lists limited, just in case someone has a lot of rep.

![bitmoji](https://render.bitstrips.com/v2/cpanel/3f8aba80-1d22-479d-a4cb-e20860bf17f8-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)

**Comment by petrspelos** [comment]
Should you decide to switch a task, or let someone else do this one, please let me know, @AbnerSquared. ❤️ Thank you
