### ISSUE TITLE
Refactor all Cast in the Miunie.Discord Project

### ISSUE THREAD

**Issue by DraxCodes** [control-net/Miunie#189]
## 🤔Issue
All casts should ideally be safely casted.

## 💡Proposed Solution
Quick refactor to handle the possibility of `null` 

**Example**
```cs
var channel = Context.Channel as SocketTextChannel;
if (channel is null)
{
    //Handle it here (maybe just a return or throw a properly formatted Exception.
}
```

## 💡Proposed Solution 2
Or you can force it to throw in casting failure `(SocketTextChannel)Context.Channel;`

**Comment by petrspelos** [comment]
That's a good point, @DraxCodes! 😊

![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)

It's also very beginner friendly. 👍
