### ISSUE TITLE
Time command improvements

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#196]
> 💡 This issue is perfect for a Miunie beginner.

## Summary

Our time command would benefit from some improvements. 😊 
Feel free to implement any one (or multiple) of these.

To learn more about what the command does, read #192.

## Possible improvements
- [x] 🟢 **[Easy]** Show user's time in the Profile command **(WIP)**
- [x] 🟢 **[Easy]** Setting user's time as an Admin
- [x] 🟠 **[Medium]** Asking about user's time in relation to yours `@Miunie time 3:00 AM for @Drax`  **(WIP)**
- [x] 🟠 **[Medium]**  Asking about message post time `@Miunie time of <message-id>`
- [x] 🟠 **[Medium]**  Asking about user's time in relation to an offset `@Miunie time for @Drax in 10 hours`

**Comment by DraxCodes** [comment]
Re-opening, was accidentally closed by the latest commit.

**Comment by DraxCodes** [comment]
Issue now completed, just needed to double check all issue points where covered.
