### ISSUE TITLE
💜 - User data takeaway & deletion

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#228]
## Summary

In order to respect user's wishes, it would be nice to provide a way for users to get a copy of all data Miunie has about them in a JSON format.

Additionally, the user should have an option to make Miunie delete all of their data.

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by AbnerSquared** [comment]
I could also tackle this one. This would create a method, probably as a `.ToString()` for MiunieUser that would display the account in JSON format. Likewise, if `IPersistentStorage` maintains files in a JSON format, I could possible take care of that using that approach instead. This would add two commands to `ProfileCommand` called `profile data` and `profile delete`. This would also modify `PhraseKey`, `Strings.resx`, and `EmbedConstructor` to display all messages that might need to be sent.

**Comment by DraxCodes** [comment]
We would prefer that you stick to one Issue at a time.

Essentially if you take an issue, don't take another until you have a PR submitted for the first.

**Comment by AbnerSquared** [comment]
Would it be possible to handle this issue as of now? I'm not sure if this one is being worked on or not.

**Comment by 1n5an1ty** [comment]
Appreciate your eagerness, but as you can see from the updates... I'm working on this.

**Comment by petrspelos** [comment]
@1n5an1ty is working on this issue.
Note that he is assigned the label "up-for-grabs" is missing. 😊
