### ISSUE TITLE
"Time For" command may require new output formating.

### ISSUE THREAD

**Issue by DraxCodes** [control-net/Miunie#235]
## Summary

Currently when you use the command like: `@Miunie time for @Draxis in 48 hours`.
It replies with the correct time that it will be but it lacks the fact that it's actually going to be that time in two days.

As you can see in the screenshot below.

![image](https://user-images.githubusercontent.com/1976592/75617675-428de080-5b5a-11ea-8d2e-15bf13b3da6d.png)

This could certainly be exactly how we want it to behave as it is showing exactly what time it should be, however I feel it could possibly benefit from having a little more info (Maybe the date too).

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by petrspelos** [comment]
Personally, I don't think date should be considered, since (as you said), we're asking about the time. 🤔

**Comment by DraxCodes** [comment]
Idk, it seems super weird just getting the time reply without a date.

**Comment by petrspelos** [comment]
My thinking is:

If I ask you, `Draxis, what time will it be for you in 128 hours?` You're not going to say:

`Well it's going to be Saturday 5th, 2020, ...`

That to me just seems weird.

**Comment by petrspelos** [comment]
Either way, I suggest we discuss this in chit chat and perhaps even get a vote going.

![bitmoji](https://sdk.bitmoji.com/render/panel/dabebf68-848a-417d-ba61-6ea1bfbc227c-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)
