### ISSUE TITLE
😎 - User Profile Title

### ISSUE THREAD

**Issue by TheSecurity** [control-net/Miunie#257]
**Bug Description**
Miunie doesn't make difference in a title when you request for someone's profile or your profile.

![image](https://user-images.githubusercontent.com/30444943/76169452-84311380-6178-11ea-95fd-b398d32b7a90.png)

**Comment by petrspelos** [comment]
Thank you, @TheSecurity! 🥇
You think you could perhaps investigate that? See if you could perhaps fix it? 😊 

![bitmoji](https://sdk.bitmoji.com/render/panel/fe4a1c10-cce9-4b4a-a43c-6e707afcc5d1-5c8412f7-ff21-4a42-9606-71a02e19d8db-v1.png?transparent=1&palette=1&width=246)

**Comment by TheSecurity** [comment]
Is there any deadline?

**Comment by petrspelos** [comment]
Nope, we didn't know about this and it's not a feature breaking bug. 😊 

You've got all the time you need. Although the sooner, the better. ❤️ 

If you need any help, feel free to reach out to any of us. 😉

**Comment by TheSecurity** [comment]
@petrspelos Ok! I'll try to do my best. :)

**Comment by petrspelos** [comment]
The simplest solution, I think, could just be displaying something like:
```
Peter's Dank Profile
```
Of course, in English there should be no `s` if the name ends with it so for example:
```
Spelos' Dank Profile
```
But that should be fairly simple to do.

----------

Of course if you have a different fix, by all means, go for it. 😊

**Comment by MNiekel** [comment]
That's unfortunate. Yesterday this issue was still open (and I wasn't sure @TheSecurity was still working on it). Now there was a pull request. Only noticed it when I was ready to commit changes. Well, it was a learning experience digging through the code anyway, so it's okay (and I should have asked!).
