### ISSUE TITLE
😎 - Refactor UrlImageConverter to remove "Using"

### ISSUE THREAD

**Issue by DraxCodes** [control-net/Miunie#260]
> 🌻 This issue is perfect for developers who are new to Miunie!

## Summary

Remove the following
```diff
public async Task<Bitmap> UrlToBitmapAsync(string url)
{
-    Bitmap bitmap;
-    var byteArray = await _httpClient.GetByteArrayAsync(url);
-    using (var ms = new MemoryStream(byteArray))
-    {
-        bitmap = new Bitmap(ms);
-    }
    return bitmap;
}
```

Instead use the `_httpClient` get `GetStreamAsync(URL_HERE)`
Use the returned stream to build a BitMap from the stream. (`new BitMap(STREAM_HERE)`)
return that new bitmap.
Ensure it works 🎉 

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either @petrspelos or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by haggardd** [comment]
I'd be happy to give this a shot 🙂

**Comment by petrspelos** [comment]
By all means, thank you @haggardd! Feel free to ask when something is unclear. 😊

**Comment by petrspelos** [comment]
Heya, @haggardd! How's the issue going, do you perhaps need help with something? 😊 

Feel free to join our [Discord server](https://discord.gg/cGhEZuk) if you'd like me to walk you through the changes. 😉

**Comment by haggardd** [comment]
Hey, yep i'll have the PR up shortly. Work got in the way 😁
