### ISSUE TITLE
🎯 - Check for empty string before sending a message

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#276]
> 👗 This issue is perfect for developers who are new to Miunie!

## Summary

The [`SendTextToChannelAsync`](https://github.com/control-net/Miunie/blob/master/src/Miunie.Discord/Impersonation.cs#L89&L95) method in our `Miunie.Discord.Impresonation` class should not attempt to send the message if the provided `text` is null or whitespace.

## How to implement

Add a simple check at the beginning of this method to return if `text` is null or whitespace. 😊

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by MNiekel** [comment]
Hi, can I be assigned to this issue?

**Comment by petrspelos** [comment]
Hello! 😊 

Absolutely, feel free to ask if anything is unclear. 😉

**Comment by MNiekel** [comment]
@petrspelos , Thanks. I made the changes and I know how I could push them. However, I would like to test it first and not sure if that is possible on my laptop (MacOS, using Atom as text editor). :-/

**Comment by MNiekel** [comment]
I am sorry, I am new to this and I think I screwed up right now. :-( I closed the issue by accident.

**Comment by petrspelos** [comment]
This issue was completed by MNiekel in 617d05b2de90c319f6db881c03676990be73db49. 😊 
Closing
