### ISSUE TITLE
🎯 - Set title in Console app

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#277]
> 🎁 This issue is perfect for developers who are new to Miunie!

## Summary

Our Console Application doesn't specify a title and displays the executable path instead:

![image](https://user-images.githubusercontent.com/21304428/76399987-ddb75f00-637f-11ea-9886-1a396a29cfbf.png)

This should really say `Miunie` instead.

## How to implement

Set the `Console.Title` to `Miunie` as the first thing in ConsoleApp/Program.cs/Main.

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by priyanshbalyan** [comment]
Hey I would like to work on this issue.
