### ISSUE TITLE
🧾 - Console Menu - List doesn't fit issue

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#278]
**Describe the bug**
When our `ConsoleMenu<T>` tries to display more items than can fit onto the Console screen, it beeps at you whenever you navigate and doesn't display all of the items.

**To Reproduce**
1. Open our ConsoleApp
2. Login with a bot that is either in a lot of server or channels
3. Go the Servers option
4. Navigate to the Guild selection or Channels selection
5. If the list is too big to fit onto your screen, you will see & hear the error when navigating

**Expected behavior**
Some form of pagination should probably be implemented. 🤔

**Comment by petrspelos** [comment]
@akaMackiee, you want to take this one? 🤔

**Comment by akaMackiee** [comment]
Sure, I can try it out! 😄

**Comment by AbnerSquared** [comment]
There is an existing `Paginator` class in place that exists in `Miunie.Discord.Embeds`. It could probably be modified to include the generic variants into a base class, and keep the `Embed` versions into a `EmbedPaginator`.
