### ISSUE TITLE
💙 - UWP Server/Channel zero state

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#279]
> 🟥🟩 **WINDOWS 10** - Version 1903+ is required for the UWP UI.
> 🟦🟨 [How to setup UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-set-up)

## Summary

When the user views the Servers or Channels section of our UWP app and the bot isn't in any server or channels, the view looks a bit weird:

![image](https://user-images.githubusercontent.com/21304428/76400782-291e3d00-6381-11ea-83c7-b68771d6cae0.png)

The Discord client for a reference has a cheeky zero state for this:

![image](https://user-images.githubusercontent.com/21304428/76400852-4521de80-6381-11ea-9ed1-7f5a7b088d18.png)

> ℹ️ Same goes for no servers.

## How to implement

We could go as simple as just displaying:

`There are no servers to browse.` and `This server doesn't contain any channels.`.

Or we could go as complex as creating our own zero-states like Discord. Either way is fine. 😊 

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by 1n5an1ty** [comment]
@petrspelos How can I set up my bot to test this scenario?

**Comment by petrspelos** [comment]
For no servers:
- Kick your bot from your test server. If that was the only server it was in, the list will be empty.

For no channels:
- Delete all of the channels in your test server, then visit it through impersonation.
