### ISSUE TITLE
🎚 - Commands Switch - Avalonia UI

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#280]
> 🌻 This issue is perfect for developers who are new to Miunie!

## Summary

Our `BotConfiguration` object used in Avalonia to for example [set the bot token](https://github.com/control-net/Miunie/blob/master/src/Miunie.Avalonia/ViewModels/MainWindowViewModel.cs#L70) contains a [`CommandsEnabled` property](https://github.com/control-net/Miunie/blob/master/src/Miunie.Core/Configuration/IBotConfiguration.cs#L20).

It this property is set to false, the bot won't respond to commands. This is useful for when you already have one instance of the bot running and want to browse the servers/channels in a different instance, but using the same token.

That way, the bot won't respond to every command twice (once from the running instance, and once from the browsing one).

## How to implement

There should be a checkbox allowing the user to toggle this property's value through the UI.

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by MNiekel** [comment]
I would like to try this but I don't know where to start. Especially which files to look for.

**Comment by 1n5an1ty** [comment]
@MNiekel I have assigned this to you. I am here if you need help if you get stuck on this. You would most likely start with the MainWindowViewModel and MainWindow.xaml you could add a toggle switch/checkbox to the MainWindow.xaml and use binding on the checked/isOn property. Then use the _miunie object from the MainWindowViewModel class to enable/disable Miunie commands. '_miunie.BotConfiguration.CommandsEnabled = true/false'

**Comment by 1n5an1ty** [comment]
@MNiekel Are you a part of our Discord server? I can't seem to find your name on there. We often talk and discuss dev efforts there. Here is the link if you need it: [Programming with Peter](https://discord.gg/cGhEZuk)

**Comment by MNiekel** [comment]
Yes I am. But I am called Sangatsuko on Discord.
