### ISSUE TITLE
⛔ - Unable to start Miunie in Avalonia UI

### ISSUE THREAD

**Issue by TheSecurity** [control-net/Miunie#283]
**Describe the bug**
When i try to start Miunie bot in Avalonia UI. It throws an exception _System.ArgumentException - Unable to load bitmap from provided data_ in MainWindowViewModel.cs - UpdateBotAvatar(). 

**UPDATE**
[Line with Exception](https://github.com/control-net/Miunie/blob/master/src/Miunie.Avalonia/Utilities/UrlImageConverter.cs#L34) - It seems like downloaded image is not possible to convert into BitMap. I am able to download the image from the [url](https://cdn.discordapp.com/avatars/559058748593930251/076bdb69aa3442a54b630d76acb53b97.png?size=128) and save it to PNG with no problems.

**Stack trace**
This exception was originally thrown at this call stack:
	Avalonia.Skia.ImmutableBitmap.ImmutableBitmap(System.IO.Stream)
	Avalonia.Skia.PlatformRenderInterface.LoadBitmap(System.IO.Stream)
	Avalonia.Media.Imaging.Bitmap.Bitmap(System.IO.Stream)
    Miunie.Avalonia.Utilities.UrlImageConverter.UrlToBitmapAsync(string) in UrlImageConverter.cs
	System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
	System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()
    Miunie.Avalonia.ViewModels.MainWindowViewModel.UpdateBotAvatar() in MainWindowViewModel.cs

**Comment by DraxCodes** [comment]
Can you confirm if this is when you try run Miunie with Avalonia or is it when you try Start her with your token.

**Comment by TheSecurity** [comment]
@DraxCodes I updated the description to the issue. I am using MiunieDev bot with her token.

**Comment by petrspelos** [comment]
I'm on it.
