### ISSUE TITLE
🎯 - Replace hardcoded ConsoleApp strings

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#301]
> 🌻 This issue is perfect for developers who are new to Miunie!

## Summary

In the ConsoleApp front-end we have a number of hardcoded strings that should actually come from `ConsoleStrings.resx`.

## How to implement

In order to complete this issue, one has to move those strings into the `ConsoleStrings.resx` file.

![image](https://user-images.githubusercontent.com/21304428/80916293-0fcdb780-8d58-11ea-8f01-bf9fcaa24118.png)

![image](https://user-images.githubusercontent.com/21304428/80916357-7226b800-8d58-11ea-9553-4f833465fa3b.png)

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by zombies808myneighbors** [comment]
I would like to help with this. I am quite new to programming, and this will be my first contribution to a project, so I will definitely have some questions for you. Also not 100% sure about github etiquette (or if there even is such a thing...). I'll go ahead and fork the repository, start digging in, and I'll reach out to you if I need help!

**Comment by petrspelos** [comment]
Absolutely, @zombies808myneighbors!

Feel free to ask about anything. There is no rush for this. 🙂

**Comment by zombies808myneighbors** [comment]
OK, I've done a bit of work and I submitted a pull request so you can see the changes I've made. So far, I've only changed the string you've shown in the picture above because I want to make sure I'm doing it correctly. Let know at your convenience and I will continue to switch over the strings or adjust according to your specifications.

**Comment by petrspelos** [comment]
You got it, @zombies808myneighbors. Just like that. 😊
