### ISSUE TITLE
⛱ - Take application screenshots for MS Store

### ISSUE THREAD

**Issue by petrspelos** [control-net/Miunie#305]
> 🟥🟩 **WINDOWS 10** - Version 1903+ is required for the UWP UI.
> 🟦🟨 [How to setup UWP](https://docs.microsoft.com/en-us/windows/uwp/get-started/get-set-up)

> 🌻 This issue is perfect for developers who are new to Miunie!

## Summary

You need to build the UWP application and take a couple of interesting screenshots.

Take inspiration from our current set of screenshots on the MS Store:

![image](https://user-images.githubusercontent.com/21304428/82293494-eabe8300-99ac-11ea-850e-fa501034fb1a.png)

## How to implement

Post your screenshots in the comments. Don't forget about Windows accent colors, dark/light theme, windows sizes, wallpapers, etc.

_You're technically not going to be recognized as a Contributor by GitHub, but commenting is going to count as a contribution on your GitHub profile. After you finish this issue, you'll have the project setup. So that's a great opportunity to take another issue._ 🙂 

If you really don't want to contribute in any other way, you will be credited in the README.md.

## Interested? 😊 

If you'd like to help us by solving this issue, just say so in the comments. ❤️ 
And don't shy away from asking any kind of question you might have.

Should you have any questions at all, feel free to contact either me (@petrspelos) or @DraxCodes on our Discord server:

[![Discord](https://img.shields.io/discord/377879473158356992?color=7289DA&label=Discord%20Server&style=for-the-badge)](https://discord.gg/cGhEZuk)

_And of course, thank you so much for contributing! 🎉 It's because of amazing people like yourself that Miunie exists._

**Comment by Haroonabdulrazaq** [comment]
I am interested, here to help

**Comment by petrspelos** [comment]
Thank you, @Haroonabdulrazaq!

Feel free to post your screenshot(s) in the comments here once you're done. =)

**Comment by vankos** [comment]
Hi, seems like @Haroonabdulrazaq  kinda lost, can i help?

**Comment by vankos** [comment]
![2020-06-30_21-31-47](https://user-images.githubusercontent.com/14087195/86165332-d4632580-bb1b-11ea-94b0-5a07d6ead112.png)
![2020-06-30_21-12-36](https://user-images.githubusercontent.com/14087195/86165336-d5945280-bb1b-11ea-81be-76b77b377051.png)
![2020-06-30_21-10-27](https://user-images.githubusercontent.com/14087195/86165338-d5945280-bb1b-11ea-96cd-43f114ce2498.png)
![2020-06-30_21-00-02](https://user-images.githubusercontent.com/14087195/86165340-d62ce900-bb1b-11ea-86bd-7b5930b00ba6.png)
![2020-06-30_20-56-02](https://user-images.githubusercontent.com/14087195/86165341-d6c57f80-bb1b-11ea-8f1a-628c7223aa1b.png)
![2020-06-30_20-41-46](https://user-images.githubusercontent.com/14087195/86165346-d6c57f80-bb1b-11ea-9ccd-c75fabd479b3.png)
![2020-06-30_20-42-02](https://user-images.githubusercontent.com/14087195/86165347-d75e1600-bb1b-11ea-940c-15699f5fb1ae.png)
![2020-06-30_20-40-36](https://user-images.githubusercontent.com/14087195/86165349-d7f6ac80-bb1b-11ea-9132-8d8b1383be28.png)
![2020-06-30_21-52-18](https://user-images.githubusercontent.com/14087195/86165524-155b3a00-bb1c-11ea-8de7-a8f529b27f2b.png)

**Comment by Liviu23** [comment]
Good job @vankos

**Comment by petrspelos** [comment]
Thank you to everyone participating, and of course vankos for providing the screenshots. :blush:
